// Style Dictionary build script for @kart/design-system tokens.
//
// Source of truth: the JSON files in tokens/src/*.json. These mirror the
// authoritative *content* spec in kart-platform's
// docs/client/kart-web/design-tokens.md — a token value change is made here
// (and, in the real platform, mirrored back into that doc), never hand-edited
// independently inside a consuming app.
//
// Output (all generated, never hand-edited):
//   projects/design-system/src/styles/tokens/base.css         -- :root, theme-independent tokens
//   projects/design-system/src/styles/tokens/theme-light.css  -- light theme semantic color tokens
//   projects/design-system/src/styles/tokens/theme-dark.css   -- dark theme semantic color tokens
//   projects/design-system/src/lib/tokens/tokens.generated.ts -- typed TS constants (Spacing, Breakpoints, Typography)
import StyleDictionary from 'style-dictionary';
import { formats, transformGroups } from 'style-dictionary/enums';

const CSS_DEST = 'projects/design-system/src/styles/tokens/';
const TS_DEST = 'projects/design-system/src/lib/tokens/';

/**
 * Custom format: typed TS constants for programmatic use (spacing math,
 * breakpoint checks in JS, etc.) — per design-system-standards.md's
 * "mirrored as typed TypeScript constants" rule.
 */
StyleDictionary.registerFormat({
  name: 'typescript/kart-constants',
  format: ({ dictionary }) => {
    const group = (prefix) =>
      dictionary.allTokens
        .filter((t) => t.path[0] === prefix)
        .map((t) => {
          const key = t.path.slice(1).join('-').replace(/-(.)/g, (_, c) => c.toUpperCase());
          return { key, value: t.value, path: t.path };
        });

    const spacing = group('spacing');
    const breakpoint = group('breakpoint');
    const radius = group('radius');
    const motionDuration = dictionary.allTokens.filter(
      (t) => t.path[0] === 'motion' && t.path[1] === 'duration',
    );
    const motionEasing = dictionary.allTokens.filter(
      (t) => t.path[0] === 'motion' && t.path[1] === 'easing',
    );

    const toObjectLiteral = (entries) =>
      entries.map(({ key, value }) => `  ${key}: '${value}',`).join('\n');

    return `/**
 * AUTO-GENERATED by Style Dictionary — do not hand-edit.
 * Source: tokens/src/*.json. Regenerate with \`npm run build:tokens\`.
 */

/** 8px-based spacing scale, mirrors the --kart-spacing-* CSS custom properties. */
export const Spacing = {
${toObjectLiteral(spacing)}
} as const;

export type SpacingToken = keyof typeof Spacing;

/** Layout breakpoints (min-width, px unless noted), mirrors the SCSS breakpoint map. */
export const Breakpoints = {
${toObjectLiteral(breakpoint)}
} as const;

export type BreakpointToken = keyof typeof Breakpoints;

/** Corner radius scale, mirrors the --kart-radius-* CSS custom properties. */
export const Radius = {
${toObjectLiteral(radius)}
} as const;

/** Motion durations, mirrors the --kart-motion-duration-* CSS custom properties. */
export const MotionDuration = {
${toObjectLiteral(
  motionDuration.map((t) => ({ key: t.path[2], value: t.value })),
)}
} as const;

/** Motion easing curves, mirrors the --kart-motion-easing-* CSS custom properties. */
export const MotionEasing = {
${toObjectLiteral(motionEasing.map((t) => ({ key: t.path[2], value: t.value })))}
} as const;

/** Typography scale, mirrors the --kart-font-* and --kart-line-height-* CSS custom properties. */
export const Typography = {
  fontFamilyBase: '${dictionary.allTokens.find((t) => t.path.join('.') === 'font.family.base').value}',
  fontFamilyDisplay: '${dictionary.allTokens.find((t) => t.path.join('.') === 'font.family.display').value}',
  fontSizeHeading1: '${dictionary.allTokens.find((t) => t.path.join('.') === 'font.size.heading-1').value}',
  fontSizeHeading2: '${dictionary.allTokens.find((t) => t.path.join('.') === 'font.size.heading-2').value}',
  fontSizeHeading3: '${dictionary.allTokens.find((t) => t.path.join('.') === 'font.size.heading-3').value}',
  fontSizeHeading4: '${dictionary.allTokens.find((t) => t.path.join('.') === 'font.size.heading-4').value}',
  fontSizeBody: '${dictionary.allTokens.find((t) => t.path.join('.') === 'font.size.body').value}',
  fontSizeCaption: '${dictionary.allTokens.find((t) => t.path.join('.') === 'font.size.caption').value}',
  fontWeightRegular: ${dictionary.allTokens.find((t) => t.path.join('.') === 'font.weight.regular').value},
  fontWeightMedium: ${dictionary.allTokens.find((t) => t.path.join('.') === 'font.weight.medium').value},
  fontWeightBold: ${dictionary.allTokens.find((t) => t.path.join('.') === 'font.weight.bold').value},
  lineHeightBody: ${dictionary.allTokens.find((t) => t.path.join('.') === 'line-height.body').value},
  lineHeightHeading: ${dictionary.allTokens.find((t) => t.path.join('.') === 'line-height.heading').value},
} as const;
`;
  },
});

const baseSD = new StyleDictionary({
  source: [
    'tokens/src/palette.json',
    'tokens/src/typography.json',
    'tokens/src/spacing.json',
    'tokens/src/radius.json',
    'tokens/src/shadow.json',
    'tokens/src/motion.json',
    'tokens/src/breakpoint.json',
  ],
  platforms: {
    css: {
      transformGroup: transformGroups.css,
      prefix: 'kart',
      buildPath: CSS_DEST,
      files: [
        {
          destination: 'base.css',
          format: formats.cssVariables,
          options: { selector: ':root', outputReferences: true },
        },
      ],
    },
    ts: {
      transformGroup: transformGroups.js,
      buildPath: TS_DEST,
      files: [{ destination: 'tokens.generated.ts', format: 'typescript/kart-constants' }],
    },
  },
});

const lightSD = new StyleDictionary({
  source: ['tokens/src/palette.json', 'tokens/src/semantic-color.light.json'],
  platforms: {
    css: {
      transformGroup: transformGroups.css,
      prefix: 'kart',
      buildPath: CSS_DEST,
      files: [
        {
          destination: 'theme-light.css',
          format: formats.cssVariables,
          filter: (token) => token.path[0] === 'color',
          options: { selector: ":root, :root[data-theme='light']", outputReferences: true },
        },
      ],
    },
  },
});

const darkSD = new StyleDictionary({
  source: ['tokens/src/palette.json', 'tokens/src/semantic-color.dark.json'],
  platforms: {
    css: {
      transformGroup: transformGroups.css,
      prefix: 'kart',
      buildPath: CSS_DEST,
      files: [
        {
          destination: 'theme-dark.css',
          format: formats.cssVariables,
          filter: (token) => token.path[0] === 'color',
          options: { selector: ":root[data-theme='dark']", outputReferences: true },
        },
      ],
    },
  },
});

await baseSD.hasInitialized;
await lightSD.hasInitialized;
await darkSD.hasInitialized;

await baseSD.buildAllPlatforms();
await lightSD.buildAllPlatforms();
await darkSD.buildAllPlatforms();

console.log('[tokens] Style Dictionary build complete.');
