/**
 * AUTO-GENERATED by Style Dictionary — do not hand-edit.
 * Source: tokens/src/*.json. Regenerate with `npm run build:tokens`.
 */

/** 8px-based spacing scale, mirrors the --kart-spacing-* CSS custom properties. */
export const Spacing = {
  xs: '4px',
  sm: '8px',
  md: '16px',
  lg: '24px',
  xl: '40px',
  xxl: '64px',
} as const;

export type SpacingToken = keyof typeof Spacing;

/** Layout breakpoints (min-width, px unless noted), mirrors the SCSS breakpoint map. */
export const Breakpoints = {
  xs: '0',
  sm: '576px',
  md: '768px',
  lg: '1024px',
  xl: '1280px',
  xxl: '1536px',
} as const;

export type BreakpointToken = keyof typeof Breakpoints;

/** Corner radius scale, mirrors the --kart-radius-* CSS custom properties. */
export const Radius = {
  none: '0',
  sm: '4px',
  md: '8px',
  lg: '16px',
  pill: '999px',
  circle: '50%',
} as const;

/** Motion durations, mirrors the --kart-motion-duration-* CSS custom properties. */
export const MotionDuration = {
  fast: '120ms',
  base: '200ms',
  slow: '320ms',
} as const;

/** Motion easing curves, mirrors the --kart-motion-easing-* CSS custom properties. */
export const MotionEasing = {
  standard: 'cubic-bezier(0.4, 0, 0.2, 1)',
} as const;

/** Typography scale, mirrors the --kart-font-* and --kart-line-height-* CSS custom properties. */
export const Typography = {
  fontFamilyBase: 'Inter, system-ui, sans-serif',
  fontFamilyDisplay: 'Inter, system-ui, sans-serif',
  fontSizeHeading1: '2.5rem',
  fontSizeHeading2: '2rem',
  fontSizeHeading3: '1.5rem',
  fontSizeHeading4: '1.25rem',
  fontSizeBody: '1rem',
  fontSizeCaption: '0.875rem',
  fontWeightRegular: 400,
  fontWeightMedium: 500,
  fontWeightBold: 700,
  lineHeightBody: 1.5,
  lineHeightHeading: 1.2,
} as const;
